config/routes.rb
Kanamobi::Application.routes.draw do
  
  resources :infos


  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "users#forgot_password", :as => "forgot_password"
  match "users/send_password_email" => "users#send_password_email", :as => "send_password_email"
  match "users/associate_user_to_campain" => "users#associate_user_to_campain", :as => "associate_user_to_campain"
  match "users/get_data" => "users#get_data", :as => "get_data"
  match "users/select_user_campain/:id" => "users#select_user_campain", :as => "select_user_campain"
  match "users/redirect_to_user_path/" => "users#redirect_to_user_path", :as => "redirect_to_user_path"
  match "users/select_user_name/:id" => "users#select_user_name", :as => "select_user_name"
  match "users/select_user_logo/:id" => "users#select_user_logo", :as => "select_user_logo"
  match "users/delete_logo/:id" => "users#delete_logo", :as => "delete_logo"
  match "users/redirecionar/:id" => "users#redirecionar", :as => "redirecionar"
  match "users/update_password" => "users#update_password", :as => "update_password"
  match "users/update_password_action" => "users#update_password_action", :as => "update_password_action"
  match "campains/filter_campains_by_date" => "campains#filter_campains_by_date", :as => "filter_campains_by_date"
  match "campains/show_date_filter/:id" => "campains#show_date_filter", :as => "show_date_filter"
  match "campains/show_date_filter_by_user_name/:name" => "campains#show_date_filter_by_user_name", :as => "show_date_filter_by_user_name"
  match "campains/get_svg" => "campains#get_svg", :as => "get_svg"
  match "campains/get_date_range" => "campains#get_date_range", :as => "get_date_range"
  match 'export_spreadsheet/:id' => 'campains#export_spreadsheet', :as => :export_spreadsheet
  match "sheets/check_errors" => "sheets#check_errors", :as => "check_errors"

  root :to => "sessions#new"

  resources :users
  resources :sessions
  resources :campains
  resources :sheets

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :contact, :email, :logo, :name, :role, :password, :password_confirmation
  attr_accessor :password

  validates_confirmation_of :password, :message => "As senhas não conferem."
  validates_presence_of :password, :on => :create, :message => "Senha não informada."
  # validates_presence_of :email, :message => "Esse campo é obrigatório."
  # validates_uniqueness_of :email, :message => "E-mail já registrado no sistema."
  # validates_presence_of :name, :message => "Nome do cliente não informado."
  # validates_uniqueness_of :name, :message => "Cliente já registrado no sistema." 
  before_save :encrypt_password

  has_many :campains, :dependent => :destroy

  mount_uploader :logo, ImageUploader

  # Metodo de autenticacao
  def self.authenticate(email, password)
  	user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
     user
    else
     nil
   end
  end

  def encrypt_password
     if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :logged_in?, :except => [:forgot_password, :send_password_email]

	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  respond_to do |format|
      if @user.save
      	# UserMailer.user_created(@user, "Registro em Kanamobi").deliver
      	session[:campain_id_for_select_tag] = nil
      	session[:user_id_for_select_tag] = @user.id
        format.html { redirect_to(@user, :notice => 'Usuário criado com sucesso.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
        format.js
      else
        format.html { render "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.js
      end
    end
	end

	def show
		@user = User.find(params[:id])
		@c = []
		if !session[:campain_id_for_select_tag].nil?
			campain = Campain.find(session[:campain_id_for_select_tag])
			redirect_to campain_path(campain)
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { 
        	if session[:campain_id_for_select_tag].nil?
        		redirect_to @user
        	else
        		campain = Campain.find(session[:campain_id_for_select_tag])
        		redirect_to campain_path(campain)
        	end
        }
        format.json { head :no_content }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    logo_path = "#{Rails.root}/public/uploads/user/logo/#{@user.id}"
    FileUtils.rm_rf logo_path
    @user.destroy

    redirect_to current_user
  end

	# pagina de 'Esqueci a senha'
	def forgot_password
		
	end

	# acao de enviar email
	def send_password_email
		user = User.find_by_email(params[:email])
	
		if user
			tokens =  [('a'..'z'),(0..9)].map{|i| i.to_a}.flatten
			new_password =  (0...5).map{ tokens[rand(tokens.length)] }.join

			user.update_attributes(:password => new_password)

			UserMailer.user_created(user, "Kanamobi Reports - Reenvio de informações de conta").deliver
			redirect_to root_url, :notice => "Email enviado com sucesso"
		else
			flash[:alert] = "Email inválido"
			redirect_to root_url
		end
	end

	def associate_user_to_campain
		if params[:first]
			puts "AAAAAAAAAAAA"
		elsif params[:second]
			puts "BBBBBBBBBBBB"
		end

		user = User.find(params[:user])
		campain = Campain.find(params[:campain])

		campain.update_attributes(:user_id => user.id)
	end

	def get_data
		user = User.find(params[:user])

		redirect_to :controller => :campains, :action => :new, :user => user.id
	end

	def select_user_campain
		user = User.find(params[:id])
		session[:user_id_for_select_tag] = user.id
		@c = user.campains.map { |campain| ["#{campain_type(campain)} | #{campain.name}", campain.id] }.insert(0, ["Selecione uma campanha", 0])
		render :partial => "select_tag_campain"
	end

	def redirect_to_user_path

		if !session[:user_id_for_select_tag].nil?
			session[:user_id_for_select_tag] = nil
			session[:campain_id_for_select_tag] = nil
			respond_to do |format|
				format.js { render :js => "window.location.href = '/users/#{current_user.id}'" }
			end

		end
	end

	def select_user_name
		@user = User.find(params[:id])
		session[:user_id_for_select_tag] = @user.id

		render :partial => "client_name"
		
	end

	def select_user_logo
		@user = User.find(params[:id])
		session[:user_id_for_select_tag] = @user.id
		
		render :partial => "client_logo"
	end

  def delete_logo
  	user = User.find(params[:id])
		
		logo_path = "#{Rails.root}/public/uploads/user/logo/#{user.id}"
    FileUtils.rm_rf logo_path
    user.update_attributes(:logo => nil)

  end

  def redirecionar
  	user = User.find(params[:id])
  	session[:campain_id_for_select_tag] = nil
  	session[:user_id_for_select_tag] = user.id
  	respond_to do |format|
				format.js { render :js => "window.location.href = '/users/#{user.id}'" }
		end
  end

  def update_password
  	@user = current_user
  	render "edit_password"
  end

  def update_password_action
  	password_salt = BCrypt::Engine.generate_salt
    password_hash = BCrypt::Engine.hash_secret(params[:password], current_user.password_salt)
    @error = nil
    @error_new_password = nil

    if current_user.password_hash != password_hash
    	@error = "Senha incorreta"
    elsif params[:new_password] == "" || params[:new_password_confirmation] == ""
    	@error_new_password = "Nova senha inválida"
    else
    	current_user.update_attributes(:password => params[:new_password])
    end

    respond_to do |format|
    	format.js
    end

  end
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_client_logo.html.erb
<% if @user && @user.role != "admin" %>
	<%= image_tag @user.logo, :id => "selected_client_logo" %>
<% end %>

app/views/users/_client_name.html.erb
<%= link_to @user.name, edit_user_path(@user), :rel => "modal:open" %>

app/views/users/_form_forgot_password.html.erb
<%= form_tag("users/send_password_email") do %>
  	
  	<div class="field">
		<span>Digite seu e-mail para recuperar a senha</span>
		<%= text_field_tag :email, params[:email] %>
	</div>
	<div class="fRight marginTop_5" style="margin-right: 40px; margin-bottom: 20px;">
		<%= submit_tag "Ok" %>
	</div>

  
<% end -%>

app/views/users/_form_password.html.erb
<script type="text/javascript">
	function validateNewPassword() {
		var newPassword = $("#new_password").attr("value");
		var newPasswordConfirmation = $("#new_password_confirmation").attr("value");	

		if (newPassword != newPasswordConfirmation) {
			$(".password-message").html("Senhas não conferem");
			$("#submit_password").attr('disabled', 'disabled');
		} else {
			$(".password-message").html("");
			$("#submit_password").removeAttr('disabled');
		}
	}
</script>

<%= form_tag("update_password_action", :multipart => true, :remote => true) do |f| %>

	<div class="field">
    <%= label_tag :password, "SENHA ATUAL*" %>
    <%= password_field_tag :password, params[:password] %>
    <span class="message hidden" id="password_error" ><%= @error %></span>
  </div>

  <div class="field">
    <%= label_tag :new_password, "NOVA SENHA*" %>
    <%= password_field_tag :new_password, params[:new_password], :id => "new_password", :onkeyup => "validateNewPassword()" %>
    <br/>
    <span class="message hidden new_password_error" ><%= @error_new_password %></span>
  </div>

  <div class="field">
    <%= label_tag :password_confirmation, "CONFIRMAÇÃO DE SENHA*" %>
    <%= password_field_tag :password_confirmation, params[:password_confirmation], :id => "new_password_confirmation", :onkeyup => "validateNewPassword()" %>
    <span class="message password-message"></span>
  </div>

	<div class="fRight marginTop_15" style="margin-right: 40px; margin-bottom: 15px;">
  	<%= submit_tag "Salvar", :id => "submit_password" %>
  </div>

<% end %>

app/views/users/_form_user.html.erb
<script type="text/javascript">
  $(document).ready(function() {
  	$('#user_logo').customFileInput();

  });

  function validateClientName(value) {
    var clientName = "<%= @user.name %>";
    clientName = clientName.toString();
    $("#client-name-message").html("");

    if (value.toUpperCase() == clientName.toUpperCase() && clientName != '') {
      console.log("aste");
      $("#submit_user").removeAttr('disabled');
      $("#client-name-message").html("")
      return;
    };
    
    var n = "<%= User.all.map { |e| "#{e.name}," } %>";
    var names = new Array();
    var tmp = "";
    for (var i = 0; i < n.length; i++) {
      if (n[i] != ',') {
         tmp += n[i];
      } else {
        names.push(tmp);
        tmp = "";
      }
    };

    if (value == '') {
      $("#client-name-message").html("Nome do cliente não informado.");
      $("#submit_user").attr('disabled', 'disabled');
      return;
    }
    for (var i = 0; i < names.length; i++) {
      if (value.toUpperCase() == names[i].toUpperCase()) {
        $("#client-name-message").html("Cliente já registrado no sistema.");
        $("#submit_user").attr('disabled', 'disabled');
        return;
      };
    };

    $("#submit_user").removeAttr('disabled');

  }

  function validateClientEmail(value) {
    var clientEmail = "<%= @user.email %>";
    clientEmail = clientEmail.toString();
    $("#client-email-message").html("");
    console.log(clientEmail);

    if (value.toUpperCase() == clientEmail.toUpperCase() && clientEmail != '') {
      $("#submit_user").removeAttr('disabled');
      $("#client-email-message").html("")
      return;
    };

    var e = "<%= User.all.map { |e| "#{e.email}," } %>";
    var emails = new Array();
    var tmp = "";
    for (var i = 0; i < e.length; i++) {
      if (e[i] != ',') {
         tmp += e[i];
      } else {
        emails.push(tmp);
        tmp = "";
      }
    };

    if (value == '') {
      $("#client-email-message").html("Email do cliente não informado.");
      $("#submit_user").attr('disabled', 'disabled');
      return;
    }
    for (var i = 0; i < emails.length; i++) {
      if (value == emails[i]) {
        $("#client-email-message").html("Cliente já registrado no sistema.");
        $("#submit_user").attr('disabled', 'disabled');
        return;
      };
    };
    $("#submit_user").removeAttr('disabled');

  }

  function validateClientPassword(password) {
    var passwordConfirmation = document.getElementById('password-confirmation').value;
    if (passwordConfirmation != '') {
      if (password != passwordConfirmation) {
        $(".client-password-message").html("Senhas não conferem.");
      } else {
        $(".client-password-message").html("");
        $("#submit_user").removeAttr('disabled');
      }
    };
  }

  function validateClientPasswordConfirmation(passwordConfirmation) {
    var password = document.getElementById('password').value;
    if (password != passwordConfirmation) {
      $(".client-password-message").html("Senhas não conferem.");
    } else {
      $(".client-password-message").html("");
      $("#submit_user").removeAttr('disabled');

    }
  }

  function validateFields() {
    var name = document.getElementById("name").value;
    var email = document.getElementById("email").value;
    var password = document.getElementById("password").value;
    var clientName = "<%= @user.name %>";
    clientName = clientName.toString();

    if (email == "") {
      $("#client-email-message").html("Email do cliente não informado.");
    } 
    if (name == "") {
      $("#client-name-message").html("Nome do cliente não informado.");
    }
    if (password == "" && clientName == "") {
      $("#client-password-message").html("Senha inválida.");
    }

    if ($("#client-email-message").html() !== "" || $("#client-name-message").html() !== "" || $("#client-password-message").html() !== "" || $("#client-password-message").html() !== "") {
      $("#submit_user").attr('disabled', 'disabled');
    };
  }
</script>

<%= form_for(@user, :multipart => true, :remote => true) do |f| %>

  <div class="field">
    <%= f.label :name, "CLIENTE*" %>
    <%= f.text_field :name, :id => "name", :onkeyup => "validateClientName(this.value)" %>
    <span class="message" id="client-name-message"></span>
  </div>

  <div class="field">
    <%= f.label :contact, "CONTATO" %>
    <%= f.text_field :contact %>
  </div>

  <div class="field">
    <div>
    	<%= f.label :logo, "LOGO" %>
    </div>
    
    <div>
	    <div class="fLeft" style="width:283px;">
		    <%= f.file_field :logo, :id => "user_logo"%>
    	</div>
    	<div id="logo_info" class="fLeft">
		    <div>Arquivo em PNG ou JPG</div>
		    <div>com 314 x 274 px</div>
    	</div>
    </div>
  </div>
  
  <div class="clear"></div>

  <div class="field">
    <%= f.label :email, "E-mail*" %>
    <%= f.text_field :email, :id => "email", :onkeyup => "validateClientEmail(this.value)" %>
    <span class="message" id="client-email-message"></span>
  </div>

  <div class="field">
    <%= f.label :password, "Senha*" %>
    <%= f.password_field :password, :id => "password", :onkeyup => "validateClientPassword(this.value)" %>
    <span class="message" id="client-password-message"></span>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, "Confirmação de senha*" %>
    <%= f.password_field :password_confirmation, :id => "password-confirmation", :onkeyup => "validateClientPasswordConfirmation(this.value)" %>
    <span class="message client-password-message" id="client-password-confirmation-message"></span>
  </div>

	<div class="fLeft marginTop_15 bold marginLeft25" style="font-size:12px;">
		<label class="field_required">*campos obrigatórios</label>
	</div>
				
	<div class="fLeft marginTop_15 marginLeft25">
		<% if !@user.id.nil? %>
			<p><%= link_to 'Apagar', @user, :id => 'cancel', :method => :delete, :data => { :confirm => 'Essa ação irá apagar o cliente e todos os seus registros. Deseja continuar?' } %></p>
		<% end %>
	</div>
					
	<div class="fRight marginTop_15" style="margin-right: 40px; margin-bottom: 15px;">
		<p class="button"><%= f.submit "Salvar", :id => "submit_user", :onclick => "validateFields()" %></p>
	</div>
  
<% end %>

app/views/users/_select_tag_campain.html.erb
<%= select_tag(:campain, options_for_select(@c, session[:campain_id_for_select_tag].to_i), :id => "campains", :onchange => "redirect(value)") %>

app/views/users/create.js.erb
<% if @user.errors.any? %>
  console.log('Error');

<% else %>
  console.log('Created');
  $.modal.close();
  $(window.location.replace("/users/<%= @user.id %>"))
<% end %>

app/views/users/edit.html.erb
<div id="modal_bar" class="menu_selected">
	<div class="modal_label">
		<span>CADASTRO DO CLIENTE</span>
	</div>
</div>

<div id="form_user">
	<%= render :partial => 'form_user' %>
</div>

app/views/users/edit_password.html.erb
<div id="modal_bar" class="menu_selected">
	<div class="modal_label">
		<span>ALTERAR SENHA</span>
	</div>
</div>

<div id="form_edit_password">
	<%= render :partial => "form_password" %>
</div>

app/views/users/forgot_password.html.erb
<div id="empty_modal_bar" class="menu_selected">
</div>
<%= render :partial => "form_forgot_password" %>

app/views/users/new.html.erb
<div id="modal_bar" class="menu_selected">
	<div class="modal_label">
		<span>CADASTRAR NOVO CLIENTE</span>
	</div>
</div>

<div id="form_user">
	<%= render :partial => 'form_user' %>
</div>

app/views/users/show.html.erb
	<div id="container_main">
	</div>

app/views/users/update.js.erb
<% if @user.errors.any? %>
  console.log('Error');
  $('#form_user').html('<%= escape_javascript(render('form_user')) %>');
<% else %>
  console.log('Created');
  $.modal.close();
  <% if session[:campain_id_for_select_tag].nil? %>
  	$(window.location.replace("/users/<%= session[:user_id_for_select_tag] %>"));
	<% else %>
		$(window.location.replace("/campains/<%= session[:campain_id_for_select_tag] %>"));
	<% end %>
<% end %>

app/views/users/update_password_action.js.erb
<% if !@error.nil? || !@error_new_password.nil? %>
	$('#form_edit_password').html('<%= escape_javascript(render('form_password')) %>');
	$("#password_error").removeClass("hidden");
	$(".new_password_error").removeClass("hidden");
<% else %>
	$(window.location.replace("/users/<%= current_user.id %>"));
<% end %>