config/routes.rb
Kanamobi::Application.routes.draw do
  
  resources :infos


  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "users#forgot_password", :as => "forgot_password"
  match "users/send_password_email" => "users#send_password_email", :as => "send_password_email"
  match "users/associate_user_to_campain" => "users#associate_user_to_campain", :as => "associate_user_to_campain"
  match "users/get_data" => "users#get_data", :as => "get_data"
  match "users/select_user_campain/:id" => "users#select_user_campain", :as => "select_user_campain"
  match "users/redirect_to_user_path/" => "users#redirect_to_user_path", :as => "redirect_to_user_path"
  match "users/select_user_name/:id" => "users#select_user_name", :as => "select_user_name"
  match "users/select_user_logo/:id" => "users#select_user_logo", :as => "select_user_logo"
  match "users/delete_logo/:id" => "users#delete_logo", :as => "delete_logo"
  match "users/redirecionar/:id" => "users#redirecionar", :as => "redirecionar"
  match "users/update_password" => "users#update_password", :as => "update_password"
  match "users/update_password_action" => "users#update_password_action", :as => "update_password_action"
  match "campains/filter_campains_by_date" => "campains#filter_campains_by_date", :as => "filter_campains_by_date"
  match "campains/show_date_filter/:id" => "campains#show_date_filter", :as => "show_date_filter"
  match "campains/show_date_filter_by_user_name/:name" => "campains#show_date_filter_by_user_name", :as => "show_date_filter_by_user_name"
  match "campains/get_svg" => "campains#get_svg", :as => "get_svg"
  match "campains/get_date_range" => "campains#get_date_range", :as => "get_date_range"
  match 'export_spreadsheet/:id' => 'campains#export_spreadsheet', :as => :export_spreadsheet
  match "sheets/check_errors" => "sheets#check_errors", :as => "check_errors"

  root :to => "sessions#new"

  resources :users
  resources :sessions
  resources :campains
  resources :sheets

end

app/models/campain.rb
class Campain < ActiveRecord::Base
  attr_accessible :from, :name, :to, :campain_type, :user_id

  validates_presence_of :campain_type, :message => "Esse campo é obrigatório"
  validates_presence_of :name, :message => "Nome da campanha não informado."
  validates_uniqueness_of :name, :message => "Já existe uma campanha com esse nome"
  validates_presence_of :from, :message => "Data inválida."
  validates_presence_of :to, :message => "Data inválida."

  has_many :sheets, :dependent => :destroy
  has_many :infos, :dependent => :destroy
  belongs_to :user

  def to_csv
  	
  end
end

app/controllers/campains_controller.rb
 require 'spreadsheet'
class CampainsController < ApplicationController

  before_filter :logged_in?

  # GET /campains
  # GET /campains.json
  def index
    @campains = Campain.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @campains }
    end
  end

  # GET /campains/1
  # GET /campains/1.json
  def show
    @number_of_rows = 30
    @campain = Campain.find(params[:id])
    @infos = @campain.infos.limit(@number_of_rows)
    @campain_type = @infos.first.campain.campain_type if !@infos.empty?
    session[:campain_id_for_select_tag] = @campain.id

    @showSMS = @campain.campain_type == 1 && !@infos.empty?
    @showLivescreen = @campain.campain_type == 2 && !@infos.empty?

    puts "SHOW SMS: #{@showSMS}"
    puts "SHOW LIVESCREEN: #{@showLivescreen}"
    puts "session > #{session[:date_range]}"

    session[:date_range2] = "#{@campain.user.campains.minimum("from").strftime("%d/%m/%Y")} A #{@campain.user.campains.maximum("to").strftime("%d/%m/%Y")}"


    if @campain.campain_type == 1
      get_chart_data_sms(@campain)
    else
      get_chart_data_livescreen(@campain.id)
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @campain }
      format.csv { render :text => @campain.to_csv }
      format.pdf do
        pdf = CampainPdf.new(@campain, session[:date_range])
        send_data pdf.render, :filename => "#{@campain.name}",
                              :type => "application/pdf",
                              :disposition => "inline"
      end
    end
  end

  # GET /campains/new
  # GET /campains/new.json
  def new

    # puts "PARAMNS: <#{params[:user]}>"

    # if !params[:user].nil?
    #  @@user = User.find(params[:user])  
    # end
    puts "USUARIO CAMPANHA: #{User.find(session[:user_id_for_select_tag]).name}"
    @campain = Campain.new
    # @user_id = @@user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @campain }
    end
  end

  # GET /campains/1/edit
  def edit
    @campain = Campain.find(params[:id])
    @user_id = @campain.user.id
  end

  # POST /campains
  # POST /campains.json
  def create
    @campain = Campain.new(params[:campain])

    @campain.user_id = session[:user_id_for_select_tag]
    
    puts params[:campain]

    respond_to do |format|
      if @campain.save
        @@user = nil
        format.html { redirect_to @campain, :notice => 'Campanha criada com sucesso.' }
        format.json { render :json => @campain, :status => :created, :location => @campain }
        format.js
      else
        format.html { render :action => "new" }
        format.json { render :json => @campain.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /campains/1
  # PUT /campains/1.json
  def update
    @campain = Campain.find(params[:id])

    respond_to do |format|
      if @campain.update_attributes(params[:campain])
        format.html { redirect_to @campain, :notice => 'Campanha atualizada com sucesso.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @campain.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /campains/1
  # DELETE /campains/1.json
  def destroy
    @campain = Campain.find(params[:id])
    @campain.destroy
    session[:campain_id_for_select_tag] = nil

    redirect_to current_user
  end

  def get_chart_data_sms(campain)
    @campainTableHelper = CampainTableHelper.find_by_campain_id(campain.id)


    if @campainTableHelper.nil?
      @campainTableHelper = CampainTableHelper.new(:campain_id => campain.id, :impacts => 0, :delivered => 0, :undelivered => 0,
      :norte => 0, :sul => 0, :nordeste => 0, :centro_oeste => 0, :sudeste => 0, :tim => 0, :vivo => 0, :oi => 0, :claro => 0)
    end

    @delivered = @campainTableHelper.delivered
    @undelivered = @campainTableHelper.undelivered

    # @operators = Info.find_all_by_campain_id(campain_id).map {|e| e.operator}.uniq
    op = []
    if !@campainTableHelper.tim != 0
      op << "Tim"
    end
    if !@campainTableHelper.oi != 0
      op << "Oi"
    end
    if !@campainTableHelper.vivo != 0
      op << "Vivo"
    end
    if !@campainTableHelper.claro != 0
      op << "Claro"
    end


    @norte = @campainTableHelper.norte
    @nordeste = @campainTableHelper.nordeste
    @centro_oeste = @campainTableHelper.centro_oeste
    @sudeste = @campainTableHelper.sudeste
    @sul = @campainTableHelper.sul

    @tim = @campainTableHelper.tim
    @oi = @campainTableHelper.oi
    @claro = @campainTableHelper.claro
    @vivo = @campainTableHelper.vivo


    # maxDate = campain.infos.map { |i| i.date }.max
    # minDate = campain.infos.map { |i| i.date }.min
    # if !maxDate.nil? && !minDate.nil?
    #   diference = ((maxDate - minDate) / 1.day).to_i
    #   if diference == 0
    #     @days = 1
    #   else
    #     @days = diference
    #   end
    # end

    @days = @campainTableHelper.date_range

  end

  def get_chart_data_livescreen(campain_id)
    @norte = Info.find_all_by_campain_id_and_region_id(campain_id, 1).count
    @nordeste = Info.find_all_by_campain_id_and_region_id(campain_id, 2).count
    @centro_oeste = Info.find_all_by_campain_id_and_region_id(campain_id, 3).count
    @sudeste = Info.find_all_by_campain_id_and_region_id(campain_id, 4).count
    @sul = Info.find_all_by_campain_id_and_region_id(campain_id, 5).count

    infos = Info.find_all_by_campain_id(campain_id)
    @total_clicks = infos.map { |i| i.clicks }.sum
    @total_prints = infos.map { |i| i.prints }.sum if !infos.first.nil? && !infos.first.prints.nil?
    @total_broadcast = infos.map { |i| i.broadcast }.sum
    if @total_broadcast > 0
      @clicks_per_broadcast = (@total_clicks / @total_broadcast).to_i
    else
      @clicks_per_broadcast = 0
    end
    maxDate = infos.map { |i| i.date }.max
    minDate = infos.map { |i| i.date }.min
    if !maxDate.nil? && !minDate.nil?
      diference = ((maxDate - minDate) / 1.day).to_i
      if diference == 0
        @days = 1
      else
        @days = diference
      end
    end
  end

  def filter_campains_by_date

          
    if !session[:user_id_for_select_tag].nil?
      user = User.find(session[:user_id_for_select_tag])

      f = params[:from]
      from = Date.strptime(f[2]+"-"+f[1]+"-"+f[0], "%Y-%m-%d")

      t = params[:to]
      to = Date.strptime(t[2]+"-"+t[1]+"-"+t[0], "%Y-%m-%d")

      session[:date_range2] = "#{f[2]+"-"+f[1]+"-"+f[0]} A #{t[2]+"-"+t[1]+"-"+t[0]}"

      # Adicionado um dia pois ao realizar a consulta o ultimo dia nao eh incluido na pesquisa (exclusivo)
      campains = Campain.all(:conditions => {:user_id => user.id, :from => from..(to + 1.day)})
      @c = campains.map { |cp| ["#{campain_type(cp)} | #{cp.name}" , cp.id] }.insert(0, ["Selecione uma campanha", 0])
      
      render :partial => "/users/select_tag_campain"
    end

  end

  def export_spreadsheet
    campain = Campain.find(params[:id])
    infos = campain.infos
    Spreadsheet.client_encoding = 'UTF-8'
    path = "#{Rails.root}/public/#{campain.id}.xls"

    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet
    sheet1.name = 'My First Worksheet'

    if campain.campain_type == 1
      sheet1.row(0).concat %w{Contato DataHora Fraseologia Estado Operadora}
      sheet1.column(0).width=15
      sheet1.column(1).width=18
      sheet1.column(2).width=40
      sheet1.column(3).width=10
      sheet1.column(4).width=10
      for i in 0..infos.count-1
        sheet1.row(i+1).concat [infos[i].impact, infos[i].date.strftime("%d/%m/%Y %H:%M"), infos[i].phraseology, infos[i].status, infos[i].operator]
      end
    else
      if !infos.first.prints.nil?
        sheet1.row(0).concat %w{DateTime Program Broadcast Clicks Region Prints}
        sheet1.column(0).width=18
        sheet1.column(1).width=40
        sheet1.column(2).width=10
        sheet1.column(3).width=10
        sheet1.column(4).width=10
        sheet1.column(5).width=10
        for i in 0..infos.count-1
          sheet1.row(i+1).concat ["#{infos[i].date.strftime("%d/%m/%Y")} #{infos[i].hour}", infos[i].phraseology, infos[i].broadcast, infos[i].clicks, Region.find(infos[i].region_id).name, infos[i].prints]
        end
      else
        sheet1.row(0).concat %w{DateTime Program Broadcast Clicks Region}
        sheet1.column(0).width=18
        sheet1.column(1).width=40
        sheet1.column(2).width=10
        sheet1.column(3).width=10
        sheet1.column(4).width=10
        for i in 0..infos.count-1
          sheet1.row(i+1).concat ["#{infos[i].date.strftime("%d/%m/%Y")} #{infos[i].hour}", infos[i].phraseology, infos[i].broadcast, infos[i].clicks, Region.find(infos[i].region_id).name]
        end
      end
    end
    
    book.write path

    send_file(path, :filename => "#{campain.name}.xls")

    # FileUtils.rm("#{Rails.root}/public/#{campain.id}.xls")

  end

  def show_date_filter
    session[:user_id_for_select_tag] = params[:id]

    render :partial => "date_filter"
  end

  def show_date_filter_by_user_name
    user = User.find_by_name(params[:name])

    session[:user_id_for_select_tag] = user.id
    render :partial => "date_filter"
  end

  def get_svg
    @campain = Campain.find(session[:campain_id_for_select_tag])
    campain_id = @campain.id
    FileUtils.mkdir_p "#{Rails.root}/public/charts/#{campain_id}"
    path = "#{Rails.root}/public/charts/#{campain_id}/"

    session[:date_range] = "#{params[:start]} A #{params[:end]}"


    if @campain.campain_type == 1 
      File.open("#{path}/delivered.svg", 'w') {|f| f.write(params[:delivered]) }
      File.open("#{path}/region.svg", 'w') {|f| f.write(params[:region]) }
      File.open("#{path}/operator.svg", 'w') {|f| f.write(params[:operator]) }

app/helpers/campains_helper.rb
module CampainsHelper

	def campain_type(campain)
		if campain.campain_type == 1
			"SMS"
		else
			"GEO MÍDIA"
		end
	end
	
end

app/views/campains/_date_filter.html.erb
<% user = User.find(session[:user_id_for_select_tag]) if session[:user_id_for_select_tag] %>
<% if !user.nil? && !user.campains.empty? %>
		<span><%= user.campains.minimum("from").strftime("%d/%m/%Y") %>&nbsp;&nbsp; A &nbsp;&nbsp;<%= user.campains.maximum("to").strftime("%d/%m/%Y") %></span>
<% else %>
<% end %>

app/views/campains/_date_range.html.erb
<%= session[:date_range2] %>

app/views/campains/edit.html.erb
<div id="modal_bar" class="menu_selected">
	<div class="modal_label">
		<span>CADASTRO DA CAMPANHA</span>
	</div>
</div>

<div id="form_campain">
	<%= render 'form_campain' %>
</div>

app/views/campains/index.html.erb
<h1>Lista de campanhas</h1>

<table id="datatable">
	<thead>
		  <tr>
    <th>Nome</th>
    <th>De</th>
    <th>Até</th>
    <th>Tipo campanha</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

	</thead>

<tbody>
	<% @campains.each do |campain| %>
  <tr>
	<td><%= campain.name %></td>
	<td><%= campain.from %></td>
	<td><%= campain.to %></td>
	<td><%= campain_type(campain) %></td>
	<td><%= link_to 'Ver', campain %></td>
	<td><%= link_to 'Editar', edit_campain_path(campain), :class => 'dialog_form' %></td>
	<td><%= link_to 'Apagar', campain, :method => :delete, :data => { :confirm => 'Essa ação irá apagar a campanha e todos os seus registros. Deseja continuar?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

app/views/campains/show.html.erb
<script type="text/javascript">
  var deliveredChart;
  var regionChart;
  var operatorChart;
  var regionChartLivescreen;

  $(function () {
    deliveredChart = new Highcharts.Chart({
        
        chart: {
            renderTo: 'delivered',
            backgroundColor:'#f5f5f5'
        },

        title: {
                text: false
        },

        tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage}%</b>',
              percentageDecimals: 1
            },

        
        credits: {
            enabled: false
        },
        
		colors: [
					'#37ad00', 
					'#fa1d00' 
				],
        
		plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        			enabled: false                    
                        		},
                   showInLegend: false,
                    size: "90%",
					center: [75, 63]

                }
		},

		series: [{
                type: 'pie',
                name: 'Quantidade',
                data: [
                    <% if @delivered != 0 %>
                      ['Entregues', <%= @delivered %>],
                    <% end %>
                    <% if @undelivered != 0 %>
                      ['Não entregues', <%= @undelivered %>]
                    <% end %>
                ]
            }]
       }); 
    });

  $(function () {
    var s = "<%= @operators %>";
    // var tamanho = parseInt(s);
    // array = new Array(s);

    // alert(new Array(s));

    // for (var i = 0; i <= array.length; i++) {
    //   console.log(array[i]);
    // };

	someVar = [{title: s, amount: 50},{title: "Food", amount: 25},{title: "Recreation", amount: 10}]

	data = $.map(someVar, function(i) { return [[i.title, i.amount]]; })
	regionChart = new Highcharts.Chart({
        
        chart: {
            renderTo: 'region',
			backgroundColor:'#f5f5f5'

        },

        title: {
                text: false
        },

        tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage}%</b>',
              percentageDecimals: 1
            },

        legend: {
	            layout: 'vertical',
	            floating: true,
	            align: 'right',
	            verticalAlign: 'bottom',
				x: 0,
				y: -5,
	            border: 0, 
	            borderRadius: 0, 
	            borderWidth: 0
		},
        
        credits: {
            enabled: false
        },
        
         plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false                    },
                    showInLegend: true,
					center: [55, 63],
					size: "90%",
                }
		},

      
		series: [{
                type: 'pie',
                name: 'Quantidade',
 				data: [
                    <% if @norte != 0 %>
		 				{
							name: 'Norte',
							color: '#ff7200',
							y: <%= @norte %>
						},
                    <% end %>
                    <% if @nordeste != 0 %>
						{
							name: 'Nordeste',
							color: '#988620',
							y: <%= @nordeste %>
						},
                    <% end %>
                    <% if @centro_oeste != 0 %>
						{
							name: 'Centro-Oeste',
							color: '#254b25',
							y: <%= @centro_oeste %>
						},
                    <% end %>
                    <% if @sudeste != 0 %>
						{
							name: 'Sudeste',
							color: '#1b2e74',
							y: <%= @sudeste %>
						},
                    <% end %>
                    <% if @sul != 0 %>
						{
							name: 'Sul',
							color: '#209883',
							y: <%= @sul %>
						},
                    <% end %>
				] 
            }]
       }); 
    });

 $(function () {
    operatorChart = new Highcharts.Chart({
        
        chart: {
            renderTo: 'operator',
            backgroundColor:'#f5f5f5'	            
        },

        title: {
                text: false
        },
        
        credits: {
            enabled: false
        },

        tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage}%</b>',
              percentageDecimals: 1
            },
        
		legend: {
	            layout: 'vertical',
	            floating: true,
	            align: 'right',
	            verticalAlign: 'bottom',
				x: -10,
				y: -5,
	            border: 0, 
	            borderRadius: 0, 
	            borderWidth: 0
		},

         plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false                    },
                    showInLegend: true,
					center: [70, 63],
					size: "90%",
                }
		},

      
		series: [{
                type: 'pie',
                name: 'Quantidade',
 				data: [
                    <% if (!@oi.nil?) && (@oi != 0) %>
						{
							name: 'OI',
							color: '#f2ae02',
							y: <%= @oi %>
						},
                    <% end %>
                    <% if (!@vivo.nil?) && (@vivo != 0) %>
						{
							name: 'VIVO',
							color: '#670794',
							y: <%= @vivo %>
						},
                    <% end %>
                    <% if (!@claro.nil?) && (@claro != 0) %>
						{
							name: 'CLARO',
							color: '#a61005',
							y: <%= @claro %>
						},
                    <% end %>
                    <% if (!@tim.nil?) && (@tim != 0) %>
		 				{
							name: 'TIM',
							color: '#3463e3',
							y: <%= @tim %>
						}
                    <% end %>
				] 
            }]
       }); 
    });

  $(function () {
    regionChartLivescreen = new Highcharts.Chart({
        
        chart: {
            renderTo: 'regionLivescreen',
            backgroundColor:'#f5f5f5'
        },

        title: {
                text: false
        },

        legend: {
              layout: 'vertical',
              floating: true,
              align: 'right',
              verticalAlign: 'bottom',
        x: -10,
        y: -5,
              border: 0, 
              borderRadius: 0, 
              borderWidth: 0
          },
        
        credits: {
            enabled: false
        },

        tooltip: {
              pointFormat: '{series.name}: <b>{point.percentage}%</b>',
              percentageDecimals: 1
		},
        
         plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false,                    },
                    showInLegend: true,
          			center: [70, 63],
          			size: "90%",
                }
		},
      
		series: [{
                type: 'pie',
                name: 'Quantidade',
 				data: [
                    <% if @norte != 0 %>
		 				{
							name: 'Norte',
							color: '#ff7200',
							y: <%= @norte %>
						},
                    <% end %>
                    <% if @nordeste != 0 %>
						{
							name: 'Nordeste',
							color: '#988620',
							y: <%= @nordeste %>
						},
                    <% end %>
                    <% if @centro_oeste != 0 %>
						{
							name: 'Centro-Oeste',
							color: '#254b25',
							y: <%= @centro_oeste %>
						},
                    <% end %>
                    <% if @sudeste != 0 %>
						{
							name: 'Sudeste',
							color: '#1b2e74',
							y: <%= @sudeste %>
						},
                    <% end %>
                    <% if @sul != 0 %>
						{
							name: 'Sul',
							color: '#209883',
							y: <%= @sul %>
						},
                    <% end %>
				] 
            }]
       }); 
    });


$(document).ready(function() {
  <% if @showSMS %>
    $("#charts").removeClass("hidden");
    $("#livescreen").addClass("hidden");
    $("#message_empty_infos").addClass("hidden");
  <% elsif @showLivescreen %>
    $("#charts").addClass("hidden");
    $("#livescreen").removeClass("hidden");
    $("#message_empty_infos").addClass("hidden");
  <% end %>
});

function exportSMS() {
  var imageURL = '';
  var chartDelivered = deliveredChart.getSVG();
  var chartRegion = regionChart.getSVG();
  var chartOperator = operatorChart.getSVG();
  var startDate = $("#date-range-field span").html().replace(/[&]nbsp[;]/gi, '').split(" A ")[0];
  var endDate = $("#date-range-field span").html().replace(/[&]nbsp[;]/gi, '').split(" A ")[1];
  $.ajax({
      type: 'POST',
      data: {delivered: chartDelivered, region: chartRegion, operator: chartOperator, start: startDate, end: endDate},
      url: "/campains/get_svg",
      async: false,
      success: function(data) {
          imageURL = data;
           // alert(imageURL);
      }

  });
}

function exportGeoMidia() {
  var imageURL = '';
  var chartRegion = regionChartLivescreen.getSVG();
  var startDate = $("#date-range-field span").html().replace(/[&]nbsp[;]/gi, '').split(" A ")[0];
  var endDate = $("#date-range-field span").html().replace(/[&]nbsp[;]/gi, '').split(" A ")[1];
  $.ajax({
      type: 'POST',
      data: {region: chartRegion, start: startDate, end: endDate},
      url: "/campains/get_svg",
      async: false,
      success: function(data) {
          imageURL = data;
           // alert(imageURL);
      }

  });
}

function waitingAnimation() {
	$("#spinner").removeClass("hidden");
	$("#bloqueio_fundo").removeClass("hidden");
	setTimeout(
		function(){
			$("#spinner").addClass("hidden");
			$("#bloqueio_fundo").addClass("hidden");
		}, ('<%= Campain.find(params[:id]).infos.count / 2 %>'));
}


</script>

<%= content_for :export  do %>
  <ul id="nav">
	<li><span>Exportar</span>
    	<ul>
        	<li><%= link_to "EXCEL (.XLS)", export_spreadsheet_path, :onclick => "waitingAnimation()" %></li>
			
			<% if @campain.campain_type == 1 %>
            	<li class="underline"><%= link_to "PDF", campain_path(@campain, :format => :pdf), :target => "_blank", :onclick => "exportSMS()" %></li>
			<% else %>
            	<li class="underline"><%= link_to "PDF", campain_path(@campain, :format => :pdf), :target => "_blank", :onclick => "exportGeoMidia()" %></li>
			<% end %>
		</ul>
	</li>    
  </ul>
<% end %>


<div id="container_main">

	<div id="spinner" class="hidden">
    	<center><%= image_tag "loading.gif" %></center>
    	<br>
    	<center> <span> A planilha está sendo gerada.</span> </center>
    	<center> <span> Por favor, aguarde...</span> </center>
  	</div>
    <div id="bloqueio_fundo" class="hidden"></div>

	<div id="charts" class="hidden">
	  <div class="impact_box" id="impacts">
		<h2>
			IMPACTOS
		</h2>
		<div id="big_number_impact">
			<%= @campainTableHelper.impacts unless @campainTableHelper.nil? %>
		</div>
	  </div>

	  <div class="chart_divider"></div>
	  
	  <div class="delivered_box">
		<h2>
			ENTREGUES
		</h2>

	  	<div id="delivered" ></div>
	  </div>

	  <div class="chart_divider"></div>
	  
	  <div class="region_box">
		<h2>
			REGIÕES
		</h2>

	  	<div id="region" ></div>
	  </div>

	  <div class="chart_divider"></div>
	  
	  <div class="operator_box">
		<h2>
			OPERADORAS
		</h2>

	  	<div id="operator" ></div>
	  </div>

	  <div class="chart_divider"></div>
	  
	  <div class="day_box" id="days">
		<h2>
			DIAS
		</h2>
		<div id="big_number_day">
			<%= @days %>
		</div>
	  </div>
	</div>
	
	<div id="livescreen" class="hidden">
		<div class="clicks_box" id="clicks">
			
			<% if !@total_prints.nil? %>
				<h2>TOTAL DE IMPRESSÕES</h2>
				<div id="big_number_clicks"><%= @total_prints %></div>
			<% else %>
				<h2>TOTAL DE CLIQUES</h2>
				<div id="big_number_clicks"><%= @total_clicks %></div>
			<% end %>

		</div>
			
		<div class="chart_divider"></div>
	
		<div class="broadcasts_box" id="broadcasts">
			<h2>
				BROADCASTS
			</h2>
			<div id="big_number_day">
        		<%= @total_broadcast %>
			</div>
		</div>
			
		<div class="chart_divider"></div>
	
		<div class="broadcast_clicks_box" id="broadcast_clicks">
			<h2>
				CLICKS POR BROADCAST
			</h2>
			<div id="big_number_day">
				<%= @clicks_per_broadcast %>
			</div>
		</div>
			
		<div class="chart_divider"></div>
	
	  	<div class="region_box">
			<h2>
				REGIÕES
			</h2>
	
			<div id="regionLivescreen" ></div>
		</div>
	
		<div class="chart_divider"></div>
	
		<div class="day_box" id="days">
			<h2>
				DIAS
			</h2>
			<div id="big_number_day">
					<%= @days %>
			</div>
		</div>
	</div>

	<div class="clear"></div>
		
	<% if !@infos.empty? %>
		<div id="tale_container">
    		<%= render :partial => "info_list" %>
		</div>
  	<% end %>

</div>