config/routes.rb
Kanamobi::Application.routes.draw do
  
  resources :infos


  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "users#forgot_password", :as => "forgot_password"
  match "users/send_password_email" => "users#send_password_email", :as => "send_password_email"
  match "users/associate_user_to_campain" => "users#associate_user_to_campain", :as => "associate_user_to_campain"
  match "users/get_data" => "users#get_data", :as => "get_data"
  match "users/select_user_campain/:id" => "users#select_user_campain", :as => "select_user_campain"
  match "users/redirect_to_user_path/" => "users#redirect_to_user_path", :as => "redirect_to_user_path"
  match "users/select_user_name/:id" => "users#select_user_name", :as => "select_user_name"
  match "users/select_user_logo/:id" => "users#select_user_logo", :as => "select_user_logo"
  match "users/delete_logo/:id" => "users#delete_logo", :as => "delete_logo"
  match "users/redirecionar/:id" => "users#redirecionar", :as => "redirecionar"
  match "users/update_password" => "users#update_password", :as => "update_password"
  match "users/update_password_action" => "users#update_password_action", :as => "update_password_action"
  match "campains/filter_campains_by_date" => "campains#filter_campains_by_date", :as => "filter_campains_by_date"
  match "campains/show_date_filter/:id" => "campains#show_date_filter", :as => "show_date_filter"
  match "campains/show_date_filter_by_user_name/:name" => "campains#show_date_filter_by_user_name", :as => "show_date_filter_by_user_name"
  match "campains/get_svg" => "campains#get_svg", :as => "get_svg"
  match "campains/get_date_range" => "campains#get_date_range", :as => "get_date_range"
  match 'export_spreadsheet/:id' => 'campains#export_spreadsheet', :as => :export_spreadsheet
  match "sheets/check_errors" => "sheets#check_errors", :as => "check_errors"

  root :to => "sessions#new"

  resources :users
  resources :sessions
  resources :campains
  resources :sheets

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :broadcast, :campain_id, :clicks, :date, :hour, :impact, :operator, :phraseology, :region_id, :status

  belongs_to :campain
  has_one :region

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, :notice => 'Info was successfully created.' }
        format.json { render :json => @info, :status => :created, :location => @info }
      else
        format.html { render :action => "new" }
        format.json { render :json => @info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, :notice => 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @info.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :impact %><br />
    <%= f.text_field :impact %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.datetime_select :hour %>
  </div>
  <div class="field">
    <%= f.label :phraseology %><br />
    <%= f.text_field :phraseology %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :operator %><br />
    <%= f.text_field :operator %>
  </div>
  <div class="field">
    <%= f.label :region %><br />
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :broadcast %><br />
    <%= f.number_field :broadcast %>
  </div>
  <div class="field">
    <%= f.label :clicks %><br />
    <%= f.number_field :clicks %>
  </div>
  <div class="field">
    <%= f.label :campain_id %><br />
    <%= f.number_field :campain_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>

<table>
  <tr>
    <th>Impact</th>
    <th>Date</th>
    <th>Hour</th>
    <th>Phraseology</th>
    <th>Status</th>
    <th>Operator</th>
    <th>Region</th>
    <th>Broadcast</th>
    <th>Clicks</th>
    <th>Campain</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.impact %></td>
    <td><%= info.date %></td>
    <td><%= info.hour %></td>
    <td><%= info.phraseology %></td>
    <td><%= info.status %></td>
    <td><%= info.operator %></td>
    <td><%= info.region %></td>
    <td><%= info.broadcast %></td>
    <td><%= info.clicks %></td>
    <td><%= info.campain_id %></td>
    <td><%= link_to 'Show', info %></td>
    <td><%= link_to 'Edit', edit_info_path(info) %></td>
    <td><%= link_to 'Destroy', info, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Impact:</b>
  <%= @info.impact %>
</p>

<p>
  <b>Date:</b>
  <%= @info.date %>
</p>

<p>
  <b>Hour:</b>
  <%= @info.hour %>
</p>

<p>
  <b>Phraseology:</b>
  <%= @info.phraseology %>
</p>

<p>
  <b>Status:</b>
  <%= @info.status %>
</p>

<p>
  <b>Operator:</b>
  <%= @info.operator %>
</p>

<p>
  <b>Region:</b>
  <%= @info.region %>
</p>

<p>
  <b>Broadcast:</b>
  <%= @info.broadcast %>
</p>

<p>
  <b>Clicks:</b>
  <%= @info.clicks %>
</p>

<p>
  <b>Campain:</b>
  <%= @info.campain_id %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>