config/routes.rb
Kanamobi::Application.routes.draw do
  
  resources :infos


  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "forgot_password" => "users#forgot_password", :as => "forgot_password"
  match "users/send_password_email" => "users#send_password_email", :as => "send_password_email"
  match "users/associate_user_to_campain" => "users#associate_user_to_campain", :as => "associate_user_to_campain"
  match "users/get_data" => "users#get_data", :as => "get_data"
  match "users/select_user_campain/:id" => "users#select_user_campain", :as => "select_user_campain"
  match "users/redirect_to_user_path/" => "users#redirect_to_user_path", :as => "redirect_to_user_path"
  match "users/select_user_name/:id" => "users#select_user_name", :as => "select_user_name"
  match "users/select_user_logo/:id" => "users#select_user_logo", :as => "select_user_logo"
  match "users/delete_logo/:id" => "users#delete_logo", :as => "delete_logo"
  match "users/redirecionar/:id" => "users#redirecionar", :as => "redirecionar"
  match "users/update_password" => "users#update_password", :as => "update_password"
  match "users/update_password_action" => "users#update_password_action", :as => "update_password_action"
  match "campains/filter_campains_by_date" => "campains#filter_campains_by_date", :as => "filter_campains_by_date"
  match "campains/show_date_filter/:id" => "campains#show_date_filter", :as => "show_date_filter"
  match "campains/show_date_filter_by_user_name/:name" => "campains#show_date_filter_by_user_name", :as => "show_date_filter_by_user_name"
  match "campains/get_svg" => "campains#get_svg", :as => "get_svg"
  match "campains/get_date_range" => "campains#get_date_range", :as => "get_date_range"
  match 'export_spreadsheet/:id' => 'campains#export_spreadsheet', :as => :export_spreadsheet
  match "sheets/check_errors" => "sheets#check_errors", :as => "check_errors"

  root :to => "sessions#new"

  resources :users
  resources :sessions
  resources :campains
  resources :sheets

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kanamobi</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application", "highcharts", "zexporting", "jquery.dd.min" %>
  <%= csrf_meta_tags %>

  <%= yield :script %>

</head>
<body>

<% campains_array = Campain.all.map { |campain| [campain.name, campain.id] } %>

<div id="page">
	
	<% if current_user %>

		<div id="dash">
			<div id="logo" class="fLeft"> <%= image_tag src="kanamobi_logo.png" %> </div>
			
			<div id="logo_cliente" class="fLeft">
				<% if !current_user.logo.path.nil? %>
					<%=  image_tag current_user.logo %>
				<% end %>
				<div id="selected_client_logo"></div>
			</div>

			<div id="client_campain" class="fLeft">

				<% if current_user.role != "admin" %>
					<% @c = Campain.find_all_by_user_id(current_user.id).map { |campain| ["#{campain_type(campain)} | #{campain.name}", campain.id] }.insert(0, ["Selecione uma campanha", 0]) %>
					<div id="client-filter">
						<div id="client-box">
							<div id="client_name">
								<div id="client_label"><span id="client-name"><%= current_user.name %></span></div>
							</div>
						</div>
					</div>
					
				<% else %>
		
					<div id="client-filter">
						<div id="client-box">
							<div id="client_label"><span id="client-name"></span></div>

							<% users_array = User.find_all_by_role("user").map { |user| [user.name, user.id] }.insert(0, ["Selecione um cliente", 0]) %>
							<%= select_tag(:user, options_for_select(users_array, session[:user_id_for_select_tag].to_i), :id => "select_tag_user", :onchange => "selectUserCampain(value)") %>			
							<%= link_to '', sign_up_path, :rel => "modal:open", :class => 'fRight add_client' %>
						</div>
					</div>
		
				<% end %>
					
				<div id="campain-filter" class="hidden fRight">
					<div id="campain-box">
						
						<div id="campain_label">
							<% if !@campain.nil? %>

								<% if current_user.role == "admin" %>
									<%= link_to "#{campain_type(@campain)} | #{@campain.name}", edit_campain_path(@campain), :rel => "modal:open" %>	
								<% else %>
									<%= campain_type(@campain) + " | " + @campain.name %>
								<% end %>

							<% else%>
								<% if current_user.role == "admin" %>
									CADASTRAR CAMPANHA
								<% else %>
									SELECIONAR CAMPANHA
								<% end %>
							<% end %>
						</div>

						<% if @c.nil? %>
				 			<% @c = [] %>
						<% end %>
						<%= render :partial => "/users/select_tag_campain" %>
						<% if current_user.role == "admin" %>
							<%= link_to '', new_campain_path, :id => "add_campain", :class => 'fRight add_campain', :rel => "modal:open"%>
						<% end %>
					</div>
				</div>

			</div>

			<div id="logout" class="fLeft">
				<p><%= link_to "Sair", log_out_path %></p>
			</div>
		</div>
	
		<div id="dash_options">
			<div id="bar" clss="hidden">
				<div id="date-period-box">
					<div id="date-range">
						<div id="date-range-field">
			      			<a href="#"></a>
			      		</div>
			      		<div id="datepicker-calendar"></div>
					</div>
		  		</div>
		
				<% if !@campain.nil? %>
					<% if current_user.role == "admin" %>
						<div id="import-box">
							<%= link_to 'Importar', "/sheets/new?campain=#{@campain.id}", :rel => "modal:open" %>	
			  			</div>
					<% end %>

					<div id="export-box">
						<%= yield :export %>
			  		</div>
				<% end %>
			
		 	</div>
			
			<% if current_user.role == "admin" %>
				<div id="hello">Olá <%= link_to current_user.name, update_password_path, :rel => "modal:open" %></div>
			<% else %>
				<div id="hello">Olá <%= current_user.name %></div>
			<% end %>

	 	</div>

		<div class="clear"></div>

	<% end %>
	
	<%= yield %>
</div>
	<div class="clear"></div>

    <div id="footer">
	    <div id="footer_content">
			
	        <span class="fLeft"><a href="http://www.kanamobi.com.br" target="_blank">Kanamobi - Copyright © 2013</a></span>
	        <div class="fRight"><span class="fRight"><a id="logo_10i9" href="http://www.10i9.com.br" target="_blank">Desenvolvido por</a></span></div>
	        
	    </div>
    </div>

</body>
</html>